services:

  gateway:
    build: ./infraestrutura/gateway
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/logs
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./infraestrutura/api
    volumes:
      - ./logs:/logs

  attacker:
    build: ./atacante
    depends_on:
      gateway:
        condition: service_healthy