services:

  gateway:
    build: ./infraestrutura/gateway
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/logs
    depends_on:
      - api

  api:
    build: ./infraestrutura/api
    volumes:
      - ./logs:/logs

  attacker:
    build: ./atacante
    depends_on:
      - gateway